# This action will run a check with the name "getsentry required checks"
# which is used by eng-pipes to determine when a commit is ready to push to.
name: Make a frontend only change
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  testing:
      # NOTE: This `name` is important! Eng-pipes is hardcoded to this
      # value and matches the check created in the getsentry/getsentry repo.
      name: getsentry required checks
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/github-script@v6
          with:
            retries: 3
            script: |
              github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: "only frontend changes",
                head_sha: context.sha,
                status: 'completed',
                conclusion: 'success',
              });
