# This action will update the nudge file.
name: Create new commit
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  new-commit:
      # NOTE: The commit message is important! Eng-pipes is hardcoded to this
      # value and matches the message used by getsentry bot.
      name: Update nudge
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - name: Update Nudge
          run: echo "# Use this file to perform arbitrary updates (i.e. create PRs and merge them) - $(date)" >| nudge
        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Eng Pipes Testing"
            file_pattern: 'nudge'
